### ISSUE TITLE
Error: You entered the wrong key

### ISSUE THREAD

**Issue by ElazarPimentel** [KoromeloDev/MindMate#3]
**Describe the bug**
Key no longer works. 

**To Reproduce**
a) App opens, 
b) ask for "Enter your key from the OpenAI site:"
c) Click on OpenAI site
d) Goes to URL https://platform.openai.com/account/api-keys
e) Gets redirected to https://platform.openai.com/api-keys
f) Ge informed "Project API keys have replaced user API keys. We recommend using project based API keys for more granular control over your resources. [Learn more](https://help.openai.com/en/articles/9186755-managing-your-work-in-platform-with-projects)"
g) Get key from new method
h) Enter into app
i) Get dialog box "Wrong key. You entered the wrong key". 

**Expected behavior**
To say "thanks for new key, use me"

**Screenshots**

**Please complete the following information**
- App version: [e.g. 1.0.0]
- Qt version: [e.g. 6.5.2]
- OS: [e.g. Windows]
- OS version: [e.g. 11]

**Additional context**

**Comment by ncorder** [comment]
Hello everyone,

I appear to have a similar issue on Trisquel GNU/Linux:

![minemate-error](https://github.com/user-attachments/assets/ae53f486-7919-4624-b1ef-1dfe3ac981bf)

Was there perhaps a recent change to the API to cause this issue?

Thank you so much for helping create such a wonderful app!

**Comment by bugs181** [comment]
> Hello everyone,
> 
> I appear to have a similar issue on Trisquel GNU/Linux:
> 
> ...
> 
> Was there perhaps a recent change to the API to cause this issue?
> 
> Thank you so much for helping create such a wonderful app!

OpenAI replaced User API keys in favor of Project API keys. My guess is that because this repo hasn't been updated in about a year, it won't work. The code would have to be updated to use the Project API keys.

**Comment by KoromeloDev** [comment]
Problem solved
